# Generated by Django 3.0.7 on 2021-04-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='Chasing',
            field=models.BooleanField(blank=True, help_text='Chasing', null=True),
        ),
    ]
