# Generated by Django 3.0.7 on 2021-04-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0002_auto_20210415_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='Approaches',
            field=models.BooleanField(blank=True, help_text='Approaches', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Climbing',
            field=models.BooleanField(blank=True, help_text='Climbing', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Eating',
            field=models.BooleanField(blank=True, help_text='Eating', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Foraging',
            field=models.BooleanField(blank=True, help_text='Foraging', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Indifferent',
            field=models.BooleanField(blank=True, help_text='Indifferent', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Kuks',
            field=models.BooleanField(blank=True, help_text='Kuks', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Moans',
            field=models.BooleanField(blank=True, help_text='Moans', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Quaas',
            field=models.BooleanField(blank=True, help_text='Quaas', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Running',
            field=models.BooleanField(blank=True, help_text='Running', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Runs_From',
            field=models.BooleanField(blank=True, help_text='Runs_From', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Tail_Flags',
            field=models.BooleanField(blank=True, help_text='Tail_Flags', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Tail_Twitches',
            field=models.BooleanField(blank=True, help_text='Tail_Twitches', null=True),
        ),
    ]
