# Generated by Django 3.0.7 on 2021-04-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0003_auto_20210415_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='id',
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Unique_Squirrel_Id',
            field=models.CharField(help_text='The unique squirrel ID', max_length=80, primary_key=True, serialize=False, unique=True),
        ),
    ]
