# Generated by Django 3.0.7 on 2021-04-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0004_auto_20210415_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='Age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenule', 'Juvenule'), ('?', '?')], help_text='Age', max_length=80),
        ),
    ]
