# Generated by Django 3.0.7 on 2021-04-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0005_auto_20210415_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='Age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('?', '?')], help_text='Age', max_length=80),
        ),
    ]
